server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/sso-server-database?schema=sso_server
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: sso_server
  jpa:
    show-sql: true
